// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/journal": {
    params: {};
  };
  "/journal/new": {
    params: {};
  };
  "/journal/entry/:entryId": {
    params: {
      "entryId": string;
    };
  };
  "/org-chart": {
    params: {};
  };
  "/org-chart/:tabName": {
    params: {
      "tabName": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/journal" | "/journal/new" | "/journal/entry/:entryId" | "/org-chart" | "/org-chart/:tabName";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/journal/_index.tsx": {
    id: "routes/journal/_index";
    page: "/journal";
  };
  "./routes/journal/new.tsx": {
    id: "routes/journal/new";
    page: "/journal/new";
  };
  "./routes/journal/entry.$entryId.tsx": {
    id: "routes/journal/entry.$entryId";
    page: "/journal/entry/:entryId";
  };
  "./routes/org-chart/_index.tsx": {
    id: "routes/org-chart/_index";
    page: "/org-chart";
  };
  "./routes/org-chart/$tabName.tsx": {
    id: "routes/org-chart/$tabName";
    page: "/org-chart/:tabName";
  };
};